name: DEV - EnergyVision Storybook
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'web/components/**'
      - 'web/.storybook/**'
      - 'web/package.json'
      - 'pnpm-lock.yaml'
jobs:
  call-workflow-passing-data:
    runs-on: ubuntu-latest
    environment:
      name: development
  steps:
    name: 'Build & deploy storybook to DEV'
    uses: ./.github/workflows/storybook-pro.yaml
    secrets: inherit
