name: PREPROD - Build & Deploy all webs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'
jobs:
  check-code:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Install pnpm 📦
        id: install-pnpm
        uses: pnpm/action-setup@v2.0.0
        with:
          version: latest
      - name: Cache pnpm modules 💾
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies 🔧
        id: install-dependencies
        run: |
          pnpm install
          pnpm install --filter energy-vision-web
      - name: Run ESLint 🔎
        id: lint
        run: |
          pnpm lint:web
      - name: Run tests 🔍
        id: test
        run: |
          pnpm test --filter energy-vision-web
      - name: log-errors-to-slack 📄
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()

  update-radix-config:
    needs: check-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        id: checkout
        uses: actions/checkout@v3
      - name: Set image tag 🏷
        shell: bash
        id: set-default-image-tag
        run: |
          echo "IMAGE_TAG_SHA=$(git rev-parse --short ${ GITHUB_SHA })" >> $GITHUB_ENV
      - name: Checkout internal 🛎️
        id: checkout-internal
        uses: actions/checkout@v3
        with:
          repository: 'equinor/energyvision-internal'
          ref: main
          token: ${{ secrets.PAT }} # Replace with ssh as per https://stackoverflow.com/questions/60222741/github-actions-and-git-clone-issue
      - name: Modify radixconfig tag for production on master branch 🗒️
        if: github.ref == 'refs/heads/main'
        run: |
          # Install pre-requisite
          python -m pip install --user ruamel.yaml
          python ci/modifyTag.py web ${{ env.IMAGE_TAG_SHA }}
          git config --global user.name 'nilsml'
          git config --global user.email 'nilsml@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/equinor/energyvision-internal
          git commit -am ${{ env.IMAGE_TAG_SHA }}
          git pull --rebase origin main
          git push origin HEAD:main
      - name: log-errors-to-slack 📄
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()

  deploy-global:
    needs: update-radix-config
    runs-on: ubuntu-latest
    environment:
      name: preprod
      url: https://web-energyvision-dev.radix.equinor.com/
    strategy:
      # The matrix approach is needed to re-use code created for satellites
      matrix:
        dataset: ['global']
    env:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.K8S_CREDENTIALS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - id: deploy-global
        uses: ./.github/workflows/deploy-websites/
        with:
          imageName: ghcr.io/equinor/energyvision/web-${{ matrix.dataset }}
          datasetName: ${{ matrix.dataset }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          sanityApiToken: ${{ secrets.SANITY_API_TOKEN }}
          sanityPreviewSecret: ${{ secrets.SANITY_PREVIEW_SECRET }}
          algoliaAppId: ${{ secrets.ALGOLIA_APP_ID }}
          algoliaApiKey: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
          environment: ${{ secrets.ENV }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()

  read-satellites:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        name: Read from satellites.json
        run: |
          MATRIX=$(cat satellites.json)
          echo ::set-output name=matrix::${MATRIX}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()

  deploy-satellites:
    needs: [deploy-global, read-satellites]
    runs-on: ubuntu-latest
    environment:
      name: preprod
    strategy:
      matrix:
        dataset: ${{ fromJson(needs.read-satellites.outputs.matrix) }}
    env:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.K8S_CREDENTIALS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - id: deploy-website
        uses: ./.github/workflows/deploy-websites/
        with:
          imageName: ghcr.io/equinor/energyvision/web-${{ matrix.dataset }}
          datasetName: ${{ matrix.dataset }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          sanityApiToken: ${{ secrets.SANITY_API_TOKEN }}
          sanityPreviewSecret: ${{ secrets.SANITY_PREVIEW_SECRET }}
          algoliaAppId: ${{ secrets.ALGOLIA_APP_ID }}
          algoliaApiKey: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
          algoliaApiKeyServer: ${{ secrets.ALGOLIA_SEARCH_API_SERVER_KEY }}
          environment: ${{ secrets.ENV }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
