name: PROD - Deploy webs
on:
  workflow_dispatch:
    inputs:
      site:
        description: 'Name of web to deploy'
        required: true
        type: choice
        options:
          - global
          - brazil
          - germany
          - argentina
          - poland
          - japan
          - storage
          - equinorfunds
          - southkorea
jobs:

  update-radix-config:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout internal 🛎️
        id: checkout-internal
        uses: actions/checkout@v3
        with:
          repository: 'equinor/energyvision-internal'
          ref: main
          token: ${{ secrets.PAT }} # Replace with ssh as per https://stackoverflow.com/questions/60222741/github-actions-and-git-clone-issue
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Promote preprod tag to prod 🗒️
        if: github.ref == 'refs/heads/main'
        shell: bash
        id: modify-radix
        run: |
          # Install pre-requisite
          python -m pip install --user ruamel.yaml
          python ci/promoteToProduction.py web ${{ github.events.inputs.site }}
          git config --global user.name 'github'
          git config --global user.email 'nilsml@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/equinor/energyvision-internal
          git commit -am ${{ env.IMAGE_TAG_SHA }}
          git pull --rebase origin main
          git push origin HEAD:main
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()


  deploy:
    needs: update-radix-config
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://equinor.com
    env:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.K8S_CREDENTIALS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKER_BUILDKIT: 1
    steps:
      - id: debug
        run: echo  To be deployed ${{ github.event.inputs.site }}
      - name: Deploy website on Radix 🚀
        id: deploy
        uses: equinor/radix-github-actions@master
        with:
          args: >
            create job
            deploy
            --token-environment
            --context production
            -a energyvision
            -e ${{ secrets.ENV }}
            -f

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
