name: PROD - Algolia Sanity Indexer
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'search/**'
      - '!search/README.md'
      - '!search/IndexArchivedNews/**'
  repository_dispatch:
    types: [sanity_publish]
jobs:
  check-code:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Install pnpm 📦
        id: install-pnpm
        uses: pnpm/action-setup@v2.0.0
        with:
          version: latest
      - name: Cache pnpm modules 💾
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies 🔧
        id: install-dependencies
        run: |
          pnpm install
          pnpm install --filter search-indexers
      - name: Run ESLint 🔎
        id: lint
        run: |
          pnpm lint:search
      - name: Run tests 🔍
        id: test
        run: |
          pnpm search-indexers test
      - name: log-errors-to-slack 📄
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
