name: PROD - Deploy all webs
on:
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  update-radix-config:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout internal 🛎️
        id: checkout-internal
        uses: actions/checkout@v3
        with:
          repository: 'equinor/energyvision-internal'
          ref: main
          token: ${{ secrets.PAT }} # Replace with ssh as per https://stackoverflow.com/questions/60222741/github-actions-and-git-clone-issue
      - name: Promote preprod tag to prod 🗒️
        if: github.ref == 'refs/heads/main'
        shell: bash
        id: modify-radix
        run: |
          # Install pre-requisite
          python -m pip install --user ruamel.yaml
          python ci/promoteAllToProduction.py web
          git config --global user.name 'github'
          git config --global user.email 'nilsml@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/equinor/energyvision-internal
          if [[ `git status --porcelain` ]]
          then
            git commit -am "🚀 Deploy all web sites to production"
            git pull --rebase origin main
            git push origin HEAD:main
          fi
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()

  deploy:
    needs: update-radix-config
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://equinor.com
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKER_BUILDKIT: 1
    steps:
      # Could be made a reusable workflow to avoid duplication
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 460b889f-89e0-4cc9-965c-31f3e7770226
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          allow-no-subscriptions: true
      - name: 'Get Azure principal token for Radix'
        shell: bash
        run: |
          token=$(az account get-access-token --resource 6dae42f8-4368-4678-94ff-3960e28e3630 --query=accessToken -otsv)
          echo "::add-mask::$token"
          echo "APP_SERVICE_ACCOUNT_TOKEN=$token" >> $GITHUB_ENV
      - name: Deploy website on Radix 🚀
        id: deploy
        uses: equinor/radix-github-actions@master
        with:
          args: >
            create job
            deploy
            --token-environment
            --context platform2
            -a equinor-web-sites
            -e ${{ secrets.ENV }}
            -f

      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
