name: PROD - Deploy webs
on:
  workflow_dispatch:
    inputs:
      site:
        description: 'Name of web to deploy'
        required: true
        type: choice
        options:
          - global
          - brazil
          - germany
          - argentina
          - poland
          - japan
          - storage
          - equinorfunds
          - southkorea
# TODO: Read tag for current version in preprod from radixconfig
# Then add this tag for prod for selected site
# Then run radix deploy for prod environment (secrets.ENV)
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://equinor.com
    env:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.K8S_CREDENTIALS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKER_BUILDKIT: 1
    steps:
      - id: debug
        run: echo  To be deployed ${{ github.event.inputs.site }}
      #- id: checkout-envis-internal
      #  uses: actions/checkout@v3
      #  with:
      #    repository: 'equinor/energyvision-internal'
      #    ref: main
      #    token: ${{ secrets.GITHUB_TOKEN }} # Replace with PAT
      - name: Deploy website on Radix 🚀
        id: deploy
        uses: equinor/radix-github-actions@master
        with:
          args: >
            create job
            deploy
            --token-environment
            --context production
            -a energyvision
            -e ${{ secrets.ENV }}
            -f

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
